version: '3'
services:
  selenium-hub:
    image: selenium/hub:latest
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:latest
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  maven:
    image: maven:latest
    depends_on:
      - selenium-hub
      - chrome
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    environment:
      - SELENIUM_HUB_HOST=selenium-hub
      - SELENIUM_HUB_PORT=4444
      - SELENIUM_NODE_HOST=chrome
      - SELENIUM_NODE_PORT=5555
    command: mvn test
