FROM openjdk:8u191-jre-alpine3.8
WORKDIR D:/Docker/GoogleAutomation
COPY target/selenium-docker.jar selenium-docker.jar
COPY target/selenium-docker-tests.jar selenium-docker-tests.jar
COPY target/lib lib
COPY testng.xml testng.xml
ENTRYPOINT java -cp selenium-docker.jar;selenium-docker-tests.jar:lib/* -DBROWSER=$BROWSER -DHUB_HOST=$HUB_HOST org.testng.TestNG ../testng.xml